### ISSUE TITLE
Parser: objectFunctionCall bug

### ISSUE THREAD

**Issue by HTML-Earth** [HTML-Earth/Spook-Compiler#14]
ball.position   = (xPos, (jumpTime + 1) * jumpHeight);

is not properly recognized:
![image](https://user-images.githubusercontent.com/4853820/56037299-3aa13400-5d2f-11e9-9ca0-2bbca41c9bf0.png)

**Comment by smath17** [comment]
yikes den er helt f'ed

**Comment by smath17** [comment]
hvor er ball.position fra?

**Comment by HTML-Earth** [comment]
> hvor er ball.position fra?

BallShader

**Comment by smath17** [comment]
Bug er fixed men ikke committed

**Comment by smath17** [comment]
Commited til "parser-refactoring" branch. rip ASsT

**Comment by HTML-Earth** [comment]
I will try to fix the ASsT
