### ISSUE TITLE
Parser: multiple variableDecl for same dataype

### ISSUE THREAD

**Issue by smath17** [HTML-Earth/Spook-Compiler#19]
Int i = 0, radius, height = 100, length = 100;

dataType (variableName | assignment) (COMMA  (variableName | assignment))*;
Det over bliver et problem med AST, siden flere variabler ligger under samme Declaration gren

**Comment by GarridoY** [comment]
Det er tilføjet i commit b4b34d3 
AST problemet vil blive fixet senere, når vi hiver fat i AST'en og får den gjort færdig.
