### ISSUE TITLE
CodeGenerator: Clean up the visit methods

### ISSUE THREAD

**Issue by HTML-Earth** [HTML-Earth/Spook-Compiler#24]
Right now the visit methods in CodeGenerator still append to the string builder, which gets reverted right after visitProgram() has been called.

```java
sb = new StringBuilder();

...

visitProgram(ast);
sb = new StringBuilder(); //hacky hack
```

The string builder appends should be moved into generateMain() / methods called by it, so we can remove the last line above.

**Comment by Rynke** [comment]
Jeg har flyttet "sb = new StringBuilder();" ned i generateMain();
