### ISSUE TITLE
AST: Multiple variable declarations for same datatype

### ISSUE THREAD

**Issue by GarridoY** [HTML-Earth/Spook-Compiler#25]
This is implemented in the Parser but is currently not in the AST. It's kind of a trivial problem and we probably shouldn't spend too much time trying to add it.
There are several other issues which are more important.

**Comment by smath17** [comment]
AST implementation in 6c7c11c
Still needs some typechecking

**Comment by smath17** [comment]
Typechecking done in 16bb50a, might have been okay earlier as well
