### ISSUE TITLE
TypeChecking: More detailed Exceptions

### ISSUE THREAD

**Issue by GarridoY** [HTML-Earth/Spook-Compiler#48]
With more detailed, it is meant that the error should say something about the thing that is wrongly typed.

The code below is "detailed":
`throw new RuntimeException("ERROR: Variable, " + variableName + " is not declared");`

While the code below is not
`throw new RuntimeException("ERROR: Variable is not declared");`

There are several RuntimeExceptions that need more detail in TypeChecking.java

**Comment by Rynke** [comment]
Fixed in 5e3e1b6
